# Generated by Django 4.1.3 on 2023-03-23 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("email", models.CharField(max_length=40)),
                ("phone", models.CharField(max_length=10)),
                ("checkin", models.CharField(max_length=10)),
                ("checkout", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rooms", models.CharField(max_length=50)),
                ("width", models.CharField(max_length=40)),
                ("adults", models.IntegerField()),
                ("childs", models.IntegerField()),
                ("amount", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Userregister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=40)),
                ("phone", models.CharField(max_length=10)),
                ("password", models.CharField(max_length=20)),
                ("confirmpassword", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=10)),
                (
                    "login_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.login",
                    ),
                ),
            ],
        ),
    ]
